premios/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from web import urls as web_urls

handler404 = 'web.views.error404'
handler500 = 'web.views.error500'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^web/', include(web_urls)),
]

web/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url('^', include('django.contrib.auth.urls')),
    url(r'^$', views.index, name='index'),
    url(r'^index/$', views.index, name='index'),
    url(r'^seguimiento/$', views.seguimiento, name='seguimiento'),
    url(r'^logout_view/$', views.logout_view, name='logout'),
    url(r'^dato/$', views.dato, name='dato'),
    url(r'^estados/$', views.estados, name='estados'),
    url(r'^ranking/$', views.ranking, name='ranking'),
    url(r'^excel_ranking/$', views.excel_ranking, name='excel_ranking'),
    url(r'^historial/$', views.historial, name='historial'),

]

web/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Tecnico(models.Model):
    tecnico_id = models.CharField(max_length=10)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.tecnico_id + " " + self.nombre

    class Meta:
        verbose_name = 'tecnico'
        verbose_name_plural = 'tecnicos'
        ordering = ('tecnico_id',)


class Cliente(models.Model):
    nombre = models.CharField(max_length=150)
    clientenro = models.CharField(max_length=100, blank=True, null=True)
    direccion = models.CharField(max_length=150)
    nodo = models.CharField(max_length=150, blank=True, null=True)
    telefono = models.CharField(max_length=150)
    email = models.EmailField(max_length=150, blank=True, null=True)
    tecnico = models.ForeignKey(
        Tecnico, related_name="clientes", on_delete=models.CASCADE)
    tecnico_compartido = models.ForeignKey(
        Tecnico, blank=True, null=True,
        default=None, related_name="clientes_comp", on_delete=models.SET_NULL)
    observacion = models.CharField(max_length=300, blank=True, null=True)
    fecha_ing = models.DateTimeField(default=timezone.now)
    fecha_liq = models.DateTimeField(
        auto_now=False, auto_now_add=False, blank=True, null=True)
    NO = "NO"
    CONTACTADO = "CT"
    VENTA = "VE"
    IN = "IN"
    LI = "LI"
    estado_choices = (
        (NO, 'No contactado'),
        (CONTACTADO, 'contactado'),
        (VENTA, 'venta confirmada'),
        (IN, "instalado"),
        (LI, 'liquidado')
    )
    estado = models.CharField(
        max_length=20, choices=estado_choices, default=NO)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = 'cliente'
        verbose_name_plural = 'clientes'
        unique_together = ("nombre", "direccion")

web/templates/web/base.html
{% load staticfiles %}
{% load web_extras %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <title>Sistema de Seguimiento de comisiones</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href='{% static "web/css/bootstrap.min.css" %}'>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href='{% static "web/css/main.css" %}'>
    {% block extraHead %}{% endblock extraHead %}
</head>
<body>
    <header class="navbar navbar-expand navbar-dark flex-column flex-md-row bd-navbar">
        <div style="width:100%" class="row">
            <div class="col-md-4 col-12">
                <a class="navbar-brand" href="{% url 'index' %}">
                    <img style="height:auto; width: 20vmax" class="logo" src="{% static 'web/img/logo.png' %}" alt="logo">
                </a>
            </div>
            <div class="col-md-4 col-12">
                <h1 class="navbar-brand titulo text-center">Comisiones por ventas</h1>
            </div>
            <div class="col-md-4 col-12 d-flex align-items-md-center">
                {% if user.is_authenticated %}
                    <div class="navbar-nav-scroll">
                        <ul class="navbar-nav navbar-expand bd-navbar-nav flex-row">
                            {% if request.user|has_group:"tecnicos" %}
                                <li class="nav-item {% block activeDato %}{% endblock activeDato %}">
                                    <a class="nav-link " href="{% url 'index' %}">Nuevo dato</a>
                                </li>
                            {% endif %}
                            <li class="nav-item {% block activeSeguimiento %}{% endblock activeSeguimiento %}">
                                <a class="nav-link" href="{% url 'seguimiento' %}">Seguimiento</a>
                            </li>
                            <li class="nav-item {% block activeRanking %}{% endblock activeRanking %}">
                                <a class="nav-link" href="{% url 'ranking' %}">Ranking</a>
                            </li>
                            {% if request.user|has_group:"comercial" or request.user|has_group:"administracion" %}
                                <li class="nav-item {% block activeHistorial %}{% endblock activeHistorial %}">
                                    <a class="nav-link" href="{% url 'historial' %}">Historial</a>
                                </li>
                            {% endif %}
                            <li class="nav-item dropdown">
                                <a class="nav-item nav-link dropdown-toggle mr-md-2" href="#" id="userDrop" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{user}}</a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDrop">
                                    <a class="dropdown-item" href="{% url 'logout' %}">Salir</a>
                                </div>
                            </li>
                        </ul>
                    </div>
                {% endif %}
            </div>    
        </div>
    </header>
    {% block content %}{% endblock content %}
    <script src='{% static "web/js/jquery-3.2.1.min.js" %}'></script>
    <script src='{% static "web/js/popper.min.js" %}'></script>
    <script src='{% static "web/js/bootstrap.min.js" %}'></script>
    <script>
        $(document).ready(function(){
            if( /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) ) {
                $(".navbar").removeClass("navbar-expand");
            }   
        });
    </script>
    {% block extraScripts %}{% endblock extraScripts %}
</body>
</html>

web/templates/web/historial.html
{% extends 'web/base.html' %}
{% load staticfiles %}
{% block activeHistorial %}active{% endblock activeHistorial %}
{% block content %}
{% if clientes %}
    <form style="margin-right:10px;"> 
    <div class="container">
        <div class="row">
            <div class="col-4 offset-4 mt-2 mb-2">
                <h2>Historial de clientes</h2>
            </div>
            <div class="col-4 mt-2 mb-2">
                <label class="mr-sm-2" for="estado">Seleccione estado</label>
                <select class="form-group custom-select mb-2" id="estado">
                    <option {% if selected == "todos" %} selected {% endif %} value"todos">Todos</option>
                    <option {% if selected == "no" %} selected {% endif %} value="no">No contactado</option>
                    <option {% if selected == "ct" %} selected {% endif %} value="ct">Contactado</option>
                    <option {% if selected == "ve" %} selected {% endif %} value="ve">Vendido</option>
                    <option {% if selected == "in" %} selected {% endif %} value="in">Instalado</option>
                    <option {% if selected == "li" %} selected {% endif %} value="li">Liquidado</option>
                </select>
            </div>
        </div>
    </div>
    <div class="row">
      <div id="tb_clientes" class="table-responsive ml-2">
            <table id="ranking" class="table table-hover col-12">
                <thead class="thead-light ">
                    <tr>
                      <th scope="col">#</th>
                      <th data-field="nombre">Nombre</th> 
                      <th data-field="clientenro">Número de cliente</th>
                      <th data-field="direccion">Dirección</th>
                      <th data-field="fecha de carga">Fecha de carga</th>
                      <th data-field="fecha de liq">Fecha de liquidación</th>
                      <th data-field="tecnico">Técnico</th>
                      <th data-field="compartido">Compartido</th>
                      <th data-field="estado">Estado</th>
                      <th data-field="observacion">Observacion</th>

                    </tr>
                </thead>
                <tbody>
                    {% for c in clientes %}
                        <tr>
                            <th scope="row">{{forloop.counter}}</th>
                            <td>{{c.nombre}}</td>
                            <td>{{c.clientenro}}</td>
                            <td>{{c.direccion}}</td>
                            <td>{{c.fecha_ing|date:'d/m/Y H:i:s'}}</td>
                            <td>{{c.fecha_liq|date:'d/m/Y H:i:s'}}</td>
                            <td>{{c.tecnico.nombre}}</td>
                            <td>{{c.tecnico_compartido.nombre}}</td>
                            <td>{{c.get_estado_display}}</td>
                            <td>{{c.observacion}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>  
      </div>
    </div>
    </form>
    {% else %}
        <div class="row">
            <h1 class="col-6 offset-4 mt-3">No hay clientes</h1>
            <div class="col-2 mt-3">
                <label class="mr-sm-2" for="estado">Seleccione estado</label>
                <select class="form-group custom-select mb-2" id="estado">
                    <option {% if selected == "todos" %} selected {% endif %} value"todos">Todos</option>
                    <option {% if selected == "no" %} selected {% endif %} value="no">No contactado</option>
                    <option {% if selected == "ct" %} selected {% endif %} value="ct">Contactado</option>
                    <option {% if selected == "ve" %} selected {% endif %} value="ve">Vendido</option>
                    <option {% if selected == "in" %} selected {% endif %} value="in">Instalado</option>
                    <option {% if selected == "li" %} selected {% endif %} value="li">Liquidado</option>
                </select>
            </div>
        </div>

  {% endif %}
{% endblock content %}
{% block extraScripts %}
<script>
    $(document).ready(function(){
        $("#estado").change(function(){
            var selected = $(this).val();
            window.location = '/web/historial/?estado=' + selected;
        });
    });
</script>
{% endblock extraScripts %}

web/templates/web/index.html
{% extends "web/base.html" %}
{% load staticfiles %}
{% block content %}
<form action="{% url 'login' %}" method="post">
    {% csrf_token %}
    <div class="form-group col-6 mx-auto">
    <label for="username">Usuario</label>
    <input name="username" type="text" class="form-control" id="username" placeholder="Usuario">
  </div>
  <div class="form-group col-6 mx-auto">
    <label for="password">Contraseña</label>
    <input name="password" type="password" class="form-control" id="password" placeholder="Contraseña">
  </div>
  <div class="form-group col-6 mx-auto">
    <button type="submit" class="btn btn-primary mx-auto">Ingresar</button>
  </div>
</form>
{% endblock content %}
{% block extraScripts %}   
{% endblock extraScripts %}

web/templates/web/main.html
{% extends 'web/base.html' %}
{% load staticfiles %}
{% block activeDato %}active{% endblock activeDato %}
{% block extraHead %}
  <link rel="stylesheet" href='{% static "web/css/toast.css" %}'>  
{% endblock extraHead %}
{% block content %}
  <div class="container-fluid">
      <main class="mt-3">
          <form id="cliente_form" method="post" action="{% url 'dato' %}">
              {% csrf_token %}
              <div class="form-group col-md-6 col-sm-12 mx-auto">
              <label for="nombre">Nombre</label>
              <input name="nombre" type="text" class="form-control" id="nombre" placeholder="Nombre" required>
            </div>
            <div class="form-group col-md-6 col-sm-12 mx-auto">
              <label for="direccion">Direccion</label>
              <input name="direccion" type="text" class="form-control"  id="direccion" placeholder="Direccion" required>
            </div>
            <div class="form-group col-md-6 col-sm-12 mx-auto">
              <label for="telefono">Teléfono</label>
              <input name="telefono" type="text" class="form-control" id="telefono" placeholder="Teléfono" required>
            </div>
            <div class="form-group col-md-6 col-sm-12 mx-auto">
              <label for="nodo">Nodo</label>
              <input name="nodo" type="text" class="form-control" id="nodo" placeholder="Nodo">
            </div>
            <div class="form-group col-md-6 col-sm-12 mx-auto">
              <label for="correo">Correo</label>
              <input name="correo" type="email" class="form-control" id="email" placeholder="Correo">
            </div>
            <div class="form-group col-md-6 col-sm-12 mx-auto">
              <label for="compartido">Ingrese el Id de su compañero de cuadrilla</label>
              <input name="compartido" type="text" class="form-control" id="compartido" placeholder="Ingrese Técnico id  de su compañero">
            </div>
            <div class="form-group col-md-6 col-sm-12 mx-auto">
              <button id="guardar" type="submit" class="btn btn-primary mx-auto">Guardar</button>
            </div>
          </form>
      </main>
  </div>
<div id="snackbar"></div>
{% endblock content %}
{% block extraScripts %}
  <script>
    $(document).ready(function(){
      msg = $.parseJSON('{{msg|escapejs}}');
      if(msg){
        toast(msg);
      }
      function toast(msg) {
      // Get the snackbar DIV
        var x = document.getElementById("snackbar");
        $(x).empty();
        x.append(msg);
        // Add the "show" class to DIV
        x.className = "show";
        // After 3 seconds, remove the show class from DIV
        setTimeout(function(){ x.className = x.className.replace("show", ""); }, 6000);
      }
      $("#guardar").click(function(event){
        event.preventDefault();
        logged = "{{logged}}";
        tecnico_comp = $("#compartido").val();
        tecnicos = JSON.parse("{{tecnicos|escapejs}}");
        if(($.inArray(tecnico_comp, tecnicos) == -1) && (tecnico_comp)){
          msg = 'Técnico compartido no válido. Ingrese el id de su compañero correctamente';
          toast(msg);
          return false;     
        }
        if(tecnico_comp == logged){
          msg = 'Está ingresando su mismo id en el campo de compartido. Ingrese el de su compañero'; 
          toast(msg)
          return false;
        }
        else{
          $("#cliente_form").submit();
        };
      });
    });
  </script>
  
{% endblock extraScripts %}

web/templates/web/ranking.html
{% extends "web/base.html"  %}
{% load web_extras %}
{% block activeRanking %}active{% endblock activeRanking %}
{% block content %}
<div class="container-fluid">
{% if tecnicos %}
    <div class="row">
        <div class="col-12 offset-4 mb-2">
            <h1>Ranking de técnicos</h1>
            <button style="display:none;" id="exportar" class="btn btn-primary offset-6">Exportar</button>
        </div>
    </div>
    <div class="row">
      <div id="tb_tecnicos" class="table-responsive">
            <table id="ranking" class="table table-hover col-12">
                <thead class="thead-light ">
                    <tr>
                      <th scope="col">#</th>
                      <th data-field="nombre">Nombre</th> 
                      <th data-field="ventas">Cantidad de ventas</th>
                      <th data-field="total">Total comisión</th>
                    </tr>
                </thead>
                <tbody>
                    {% for tec in tecnicos %}
                        <tr>
                            <th scope="row">{{forloop.counter}}</th>
                            <td>{{tec.nombre}}</td>
                            <td>{{tec.ventas}}</td>
                            <td>{{"$"|addstr:tec.comision}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>  
      </div>
    </div>
    {% else %}
        <h1 class="offset-4 mt-3">No hay clientes instalados</h1> 
  {% endif %}
</div>
{% endblock content %}
{% block extraScripts %}
<script>
    $(document).ready(function() {
      var grupo = JSON.parse("{{grupo|escapejs}}");
      var isMobile = /Android|webOS|iPhone|iPad|iPod|BlackBerry/i.test(navigator.userAgent) ? true : false;
      $.each(grupo, function(key, value){
        if ((value == 'administracion')&&(!isMobile)){
          $('#exportar').css('display', 'block');
        };
      })
      $("#exportar").click(function(event){
        window.location = '/web/excel_ranking/'
      });
  });
  </script>
{% endblock extraScripts %}

web/templates/web/seguimiento.html
{% extends "web/base.html"  %}
{% load staticfiles %}
{% block activeSeguimiento %}active{% endblock activeSeguimiento %}
{% block extraHead %}
  <link rel="stylesheet" href='{% static "web/css/seguimiento.css" %}'>  
{% endblock extraHead %}
{% block content %}
<div class="container-fluid">
      <div class="row">
          <div class="col col-sm-9 offset-4 mt-3 mb-3">
              <h1>Potenciales clientes</h1>
          </div>
      </div>
      <div class="row">
        <form id="seguimiento" class="col-12" id="clientes" method="post" action="{% url 'estados' %}">
        {% csrf_token %}
            <div class="table-responsive">
              <table id="tb_clientes" class="table table-hover">
                  <thead class="thead-light ">
                      <tr>
                        <th data-field="nombre">Nombre</th>
                        <th data-field="clientenro">Número de cliente</th>
                        <th data-field="direccion">Dirección</th>
                        <th data-field="telefono">Teléfono</th>
                        <th data-field="nodo">Nodo</th>
                        <th data-field="correo">Correo</th>
                        <th data-field="tecnico">Tecnico</th>
                        <th data-field="compartido">Compartido con</th>
                        <th data-field="fecha_ing">Fecha de Carga</th>
                        <th data-field="observacion">Observación</th>
                        <th data-field="estado">Estado</th>
                      </tr>
                  </thead>
                  <tbody>
                      {% for cliente in clientes %}
                          <tr>
                              <td>{{cliente.nombre}}</td>
                              <td>
                                <div class="form-group">
                                  <input class="form-control clientenro" disabled name="clientenro-{{cliente.pk}}" id="clientenro" value="{{cliente.clientenro}}" type="text">
                                </div>
                              </td>
                              <td>{{cliente.direccion}}</td>
                              <td>{{cliente.telefono}}</td>
                              <td>{{cliente.nodo}}</td>
                              <td>{{cliente.email}}</td>
                              <td>{{cliente.tecnico.nombre}}</td>
                              {% if cliente.tecnico_compartido %}
                                <td>{{cliente.tecnico_compartido.nombre}}</td>
                              {% else %}
                                <td></td>  
                              {% endif %}
                              <td>{{cliente.fecha|date:'d/m/Y H:i:s'}}</td>
                              <td>
                                <div class="form-group disabled">
                                  <textarea style="resize:none;" disabled cols=80 maxlength=300 name="obs-{{cliente.pk}}" class="form-control com" id="obs-{{cliente.pk}}" rows=4>{% if cliente.observacion %}
                                    {{cliente.observacion}}
                                  {% endif %} 
                                  </textarea>
                                </div>
                              </td>
                              <td>
                                  <div class="form-check form-check-inline disabled">
                                    <label class="form-check-label">
                                      <input id="estado-{{cliente.pk}}" name="estado-{{cliente.pk}}" disabled class="form-check-input com" type="radio" value="no" {% if cliente.estado == "NO" or cliente.estado == ""  %} checked="checked"{% endif %}
                                      > No contactado   
                                    </label>
                                  </div>
                                  <div class="form-check form-check-inline disabled">
                                    <label class="form-check-label">
                                      <input id="estado-{{cliente.pk}}" disabled name="estado-{{cliente.pk}}" class="form-check-input com" type="radio" value="ct" {% if cliente.estado == "CT" %}
                                        checked="checked"
                                      {% endif %}> Contactado
                                    </label>
                                  </div>
                                  <div class="form-check form-check-inline disabled">
                                    <label class="form-check-label">
                                      <input  id="estado-{{cliente.pk}}" disabled name="estado-{{cliente.pk}}" class="form-check-input com" type="radio" value="ve" {% if cliente.estado == "VE" %}checked="checked"
                                      {% endif %} > Vendido
                                    </label>
                                  </div>
                                  <div class="form-check form-check-inline disabled">
                                    <label class="form-check-label">
                                      <input  id="estado-{{cliente.pk}}" disabled name="estado-{{cliente.pk}}" class="form-check-input com" type="radio" value="in" {% if cliente.estado == "IN" %}checked="checked"
                                      {% endif %} > Instalado
                                    </label>
                                  </div>
                                  <div class="form-check form-check-inline disabled">
                                    <label class="form-check-label">
                                      <input  id="estado-{{cliente.pk}}" disabled name="estado-{{cliente.pk}}" class="form-check-input adm" type="radio" value="li"> Liquidado
                                    </label>
                                  </div>
                              </td>
                          </tr>
                      {% endfor %}
                  </tbody>
              </table>
            </div>
        <div class="form-group col-md-6 col-sm-12 mx-auto">
              <button style="display:None;" id="guardar" type="submit" class="btn btn-primary mx-auto">Guardar</button>
        </div>
      </form>
    </div>
</div>
{% endblock content %}
{% block extraScripts %}
  <script>
    $(document).ready(function() {
      var grupo = JSON.parse("{{grupo|escapejs}}");
      console.log(grupo);
      $.each(grupo, function(key, value){
        if (value == 'comercial'){
          console.log($(".form-check-input.com").prop("disabled"));
          $(".form-check-input.com").prop("disabled", false);
          console.log($(".form-check-input.com").prop("disabled"));
          $('#guardar').css('display', 'block');
          $(".form-control.com").prop("disabled", false);
          $(".form-control.clientenro").each(function(key,value){  
            $(this).prop("disabled", false)
          });
        };
        if (value == 'administracion'){
          $(".form-check-input.adm").prop("disabled", false);
          $('#guardar').css('display', 'block');
        };
      })
    });
  </script>
{% endblock extraScripts %}